# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'imdb' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for imdb
  pod 'Alamofire'
  pod 'AlamofireImage'
  pod 'ParallaxHeader', '3.0.0'

  
  target 'imdbTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'imdbUITests' do
    # Pods for testing
  end

end
